// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BankConnection is an autogenerated mock type for the BankConnection type
type BankConnection struct {
	mock.Mock
}

// GetBalanceByID provides a mock function with given fields: id
func (_m *BankConnection) GetBalanceByID(id int) (float64, error) {
	ret := _m.Called(id)

	var r0 float64
	if rf, ok := ret.Get(0).(func(int) float64); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
